name: Sync Translations with POEditor

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  sync-translations:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4

      # Upload translations to POEditor
      - name: Upload translations to POEditor
        run: |
          # Define the files and languages
          declare -A files
          # files["en"]="src/assets/locale/messages.xlf"
          # files["fr"]="src/assets/locale/messages.fr.xlf"
          # files["de"]="src/assets/locale/messages.de.xlf"
          files["it"]="src/assets/locale/messages.it.xlf"

          for lang in "${!files[@]}"; do
            echo "Uploading ${files[$lang]} for language $lang"
            response=$(curl -s -X POST https://api.poeditor.com/v2/projects/upload \
              -F "api_token=56acaf6808f07eb52c5b39a3abea19a7" \
              -F "id=740876" \
              -F "language=$lang" \
              -F "updating=terms_translations" \
              -F "file=@${files[$lang]}")

            echo "Response: $response"
            status=$(echo $response | jq -r '.response.status')

            if [ "$status" != "success" ]; then
              echo "Error uploading file for $lang: $response"
              exit 1
            fi

            echo "Waiting for 1 minutes to respect rate limits..."
            sleep 60
          done

      # Export translations from POEditor
      - name: Export translations from POEditor
        run: |
          # Define languages
          languages=("it")

          for lang in "${languages[@]}"; do
            echo "Exporting translations for language $lang"
            response=$(curl -s -X POST https://api.poeditor.com/v2/projects/export \
              -F "api_token=56acaf6808f07eb52c5b39a3abea19a7" \
              -F "id=740876" \
              -F "language=$lang" \
              -F "type=xlf")

            echo "Response: $response"
            status=$(echo $response | jq -r '.response.status')
            # Download the file from the url
            if [ "$status" == "success" ]; then
              url=$(echo $response | jq -r '.result.url')
              curl -s -o src/assets/translated/messages.$lang.xlf $url
            else
              echo "Error exporting translations for $lang: $response"
              exit 1
            fi

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "Ayush8923"
          git config user.email "ayuuniyal7@gmail.com"
          git remote set-url origin https://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@github.com/Ayush8923/POEditor-Workflow.git

      # Create a new branch for updates
      - name: Create new branch for translations
        run: |
          git checkout master
          git checkout -b update-translations
          git add src/assets/translated/*.xlf
          git commit -m "Update translations from POEditor"

      # Push the new branch to the repository
      - name: Push changes
        run: git push origin update-translations

      # Create pull request
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-translations
          base: master
          title: "Update translations from POEditor"
          body: |
            This PR updates the translations exported from POEditor.
