name: Sync Translations with POEditor

on:
  push:
    branches:
      - master

jobs:
  sync-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4

      # Upload translations to POEditor
      - name: Upload translations to POEditor
        run: |
          # Define the files and languages
          declare -A files
          # files["en"]="src/assets/locale/messages.xlf"
          # files["fr"]="src/assets/locale/messages.fr.xlf"
          # files["de"]="src/assets/locale/messages.de.xlf"
          files["it"]="src/assets/locale/messages.it.xlf"

          for lang in "${!files[@]}"; do
            echo "Uploading ${files[$lang]} for language $lang"
            response=$(curl -s -X POST https://api.poeditor.com/v2/projects/upload \
              -F "api_token=56acaf6808f07eb52c5b39a3abea19a7" \
              -F "id=740876" \
              -F "language=$lang" \
              -F "updating=terms_translations" \
              -F "file=@${files[$lang]}")

            echo "Response: $response"
            status=$(echo $response | jq -r '.response.status')

            if [ "$status" != "success" ]; then
              echo "Error uploading file for $lang: $response"
              exit 1
            fi

            echo "Waiting for 2 minutes to respect rate limits..."
            sleep 120
          done

      # Export updated translations from POEditor
      - name: Export translations from POEditor
        run: |
          # Define languages
          # languages=("en" "fr" "de" "it")
          languages=("it")

          for lang in "${languages[@]}"; do
            echo "Exporting translations for language $lang"
            response=$(curl -s -X POST https://api.poeditor.com/v2/projects/export \
              -F "api_token=56acaf6808f07eb52c5b39a3abea19a7" \
              -F "id=740876" \
              -F "language=$lang" \
              -F "type=xlf")

            echo "Response: $response"
            url=$(echo $response | jq -r '.result.url')

            if [ -z "$url" ] || [ "$url" = "null" ]; then
              echo "Error: Export API did not return a valid URL for $lang"
              exit 1
            fi

            curl -L $url -o src/assets/locale/messages.$lang.xlf
            echo "Downloaded messages.$lang.xlf successfully"
            echo "Waiting for 2 minutes to respect rate limits..."
            sleep 120
          done

      # Commit and create a new PR
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create new branch for translations
        run: |
          git checkout -b update-translations
          git add src/assets/locale/messages.*.xlf
          git commit -m "Update translations from POEditor"

      - name: Push changes
        run: git push origin update-translations

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: update-translations
          title: "Update translations from POEditor"
          body: "This PR updates the translations exported from POEditor."
          labels: translations
